# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import eoffice


class Ui_dialog(object):
    def setupUi(self, dialog):
        dialog.setObjectName("dialog")
        dialog.resize(543, 300)
        self.pushButton = QtWidgets.QPushButton(dialog)
        self.pushButton.setGeometry(QtCore.QRect(380, 20, 101, 51))
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(dialog)
        self.label.setGeometry(QtCore.QRect(380, 200, 131, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(dialog)
        self.label_2.setGeometry(QtCore.QRect(380, 230, 141, 16))
        self.label_2.setObjectName("label_2")
        self.label_5 = QtWidgets.QLabel(dialog)
        self.label_5.setGeometry(QtCore.QRect(380, 250, 161, 21))
        self.label_5.setObjectName("label_5")
        self.pushButton_2 = QtWidgets.QPushButton(dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(380, 90, 101, 41))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(dialog)
        self.pushButton_3.setGeometry(QtCore.QRect(380, 140, 101, 41))
        self.pushButton_3.setObjectName("pushButton_3")
        self.textEdit = QtWidgets.QTextEdit(dialog)
        self.textEdit.setGeometry(QtCore.QRect(10, 30, 361, 31))
        self.textEdit.setObjectName("textEdit")
        self.textEdit_2 = QtWidgets.QTextEdit(dialog)
        self.textEdit_2.setGeometry(QtCore.QRect(10, 70, 361, 201))
        self.textEdit_2.setObjectName("textEdit_2")

        self.retranslateUi(dialog)

        self.pushButton_3.clicked.connect(dialog.close)
        self.pushButton_2.clicked.connect(self.textEdit_2.clear)
        self.pushButton_2.clicked.connect(self.textEdit.clear)

        self.pushButton.clicked.connect(self.getShell)  #添加上攻击按钮的触发，去触发getShell方法，但是这里没有这个方法，所以在下面去定义这个方法来调用
        QtCore.QMetaObject.connectSlotsByName(dialog)

    def getShell(self):            #定义这个方法来获取攻击脚本的函数
        if self.textEdit.toPlainText() == "":
            target_url = 'http://www.baidu.com'
        else:
            target_url = self.textEdit.toPlainText()   #从用户输入的文本框里获取函数
            re = eoffice.getShell(target_url)   #调用攻击脚本，并赋值给re，去输出到回显框
            self.textEdit_2.setText(re)    #函数返回的结果输出到回显框

    def retranslateUi(self, dialog):
        _translate = QtCore.QCoreApplication.translate
        dialog.setWindowTitle(_translate("dialog", "泛微E-office一键getshell    by:一个辣鸡"))
        self.pushButton.setText(_translate("dialog", "开始"))
        self.label.setText(_translate("dialog", "自用工具请勿外传"))
        self.label_2.setText(_translate("dialog", "FaFo语法："))
        self.label_5.setText(_translate("dialog", "app=泛微-EOffice"))
        self.pushButton_2.setText(_translate("dialog", "清除"))
        self.pushButton_3.setText(_translate("dialog", "关闭"))
        self.textEdit.setPlaceholderText(_translate("dialog", "请输入URL，例如：HTTP://www.baidu.com:port/"))
        self.textEdit_2.setPlaceholderText(_translate("dialog", "此处为回显"))